[[validating-arguments]]
== Validating arguments

YAVI supports validating arguments of a constructor or factory method *before creating an object* with Arguments Validator.

This is one of YAVI's unique features.

=== Define and obtain an Arguments Validator instance
Arguments Validator, as the name implies, is a Validator for arguments.

A normal Validator, like Bean Validation, validates if the values are valid for the object to which the values are set, while the Arguments Validator validates that *the arguments* set to the Object are valid.

Since an object is created before validation in a normal Validator, there is a possibility of creating an object in an incomplete state temporarily.
For example, even if the constraint of `notNull()` is imposed on the Validator side,
if the `null` check is implemented in the constructor, this `null` check will work before the validation by Validator is executed.

The Arguments Validator *creates an object after validation*, so you don't have to worry about an incomplete object.


[source,java]
----
public class Person {
    public Person(String name, String email, Integer age) {
        // ...
    }

    public static Arguments3Validator<String, String, Integer, Person> validator = ArgumentsValidatorBuilder
        .of(Person::new)
        .builder(b -> b
            ._string(Arguments1::arg1, "name", c -> c.notBlank().lessThanOrEqual(100)) // Constrains onf the first argument of Person::new
            ._string(Arguments2::arg2, "email", c -> c.notBlank().lessThanOrEqual(100).email()) // Constrains onf the second argument of Person::new
            ._integer(Arguments3::arg3, "age", c -> c.greaterThanOrEqual(0).lessThan(200))) // Constrains onf the third argument of Person::new
        .build();
}
----

The Arguments Validator can be used as follows:

[source,java]
----
Validated<Person> personValidated = Person.validator.validate("Jone Doe", "jdoe@example.com", 30);
----

`am.ik.yavi.arguments.Arguments1Validator` to `am.ik.yavi.arguments.Arguments16Validator` are available.

Arguments Validator is useful, but it can be a bit verbose to define. Since it is Type-Safe, it is not possible to define something that does not fit the type, but it feels like a puzzle that fits the type.
Building the Arguments Validator can be simplified by "<<define-validator-for-a-single-value>>" and "<<combining-validators>>".

=== Validating method arguments

Arguments Validator can be used for validating method arguments as well.

[source,java]
----
// From https://beanvalidation.org/
public class UserService {
    public User createUser(/* @Email */ String email,
                         /* @NotNull */ String name) {
        // ...
    }
}
----

The arguments for `UserService.createUser` in the above example can be validated as follows:

[source,java]
----
Arguments3Validator<UserService, String, String, User> validator = ArgumentsValidatorBuilder
    .of(UserService::createUser)
    .builder(b -> b
        ._object(Arguments1::arg1, "userService", c -> c.notNull())
        ._string(Arguments2::arg2, "email", c -> c.email())
        ._string(Arguments3::arg3, "name", c -> c.notNull()))
    .build();

UserService userService = new UserService();
Validated<User> userValidated = validator.validate(userService, "jdoe@example.com", "John Doe");
----

NOTE: `void` cannot be used as return type while `java.lang.Void` is available.

[[define-validator-for-a-single-value]]
=== Define Validator for a single value

If you just want to define `Arguments1Validator` for a single `String` or `Integer` etc, you can write:

[source,java]
----
StringValidator<String> nameValidator = StringValidatorBuilder
    .of("name", c -> c.notBlank().lessThanOrEqual(100))
    .build();  // -> extends Arguments1Validator<String, String>

StringValidator<String> emailValidator = StringValidatorBuilder
    .of("email", c -> c.notBlank().lessThanOrEqual(100).email())
    .build();  // -> extends Arguments1Validator<String, String>

IntegerValidator<Integer> ageValidator = IntegerValidatorBuilder
    .of("age", c -> c.greaterThanOrEqual(0).lessThan(200))
    .build();  // -> extends Arguments1Validator<Integer, Integer>

Validated<String> nameValidated = nameValidator.validate("Jone Doe");
Validated<String> emailValidated = nameValidator.validate("jdoe@example.com");
Validated<Integer> ageValidated = nameValidator.validate(30);
----

You can convert it to a Value Object after validation by using the `andThen` method as follows:

[source,java]
----
StringValidator<Name> nameValidator = StringValidatorBuilder
    .of("name", c -> c.notBlank().lessThanOrEqual(100))
    .build()
    .andThen(name -> new Name(name)); // -> extends Arguments1Validator<String, Name>

StringValidator<Email> emailValidator = StringValidatorBuilder
    .of("email", c -> c.notBlank().lessThanOrEqual(100).email())
    .build()
    .andThen(email -> new Email(email)); // -> extends Arguments1Validator<String, Email>

IntegerValidator<Age> ageValidator = IntegerValidatorBuilder
    .of("age", c -> c.greaterThanOrEqual(0).lessThan(200))
    .build()
    .andThen(age -> new Age(age)); // -> extends Arguments1Validator<Integer, Age>

Validated<Name> nameValidated = nameValidator.validate("Jone Doe");
Validated<Email> emailValidated = nameValidator.validate("jdoe@example.com");
Validated<Age> ageValidated = nameValidator.validate(30);
----

If you want to create an `Arguments1Validator` for a `List`, you can "lift" a `Validator` for the element of the list as follows:

[source,java]
----
Arguments1Validator<Iterable<String>, List<Email>> emailsValidator = ArgumentsValidators.liftList(emailValidator);
Validated<List<Email>> emailsValidated = emailsValidator.validate(List.of("foo@example.com", "bar@example.com"));
----


These "small Validators" can be very powerful parts by using the Validator combinators described in "<<combining-validators>>".