name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11.x
    - name: Cache Maven
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Generate Document
      if: github.ref == 'refs/heads/main'
      run: ./mvnw -V clean package
    - name: Upload Document
      if: github.ref == 'refs/heads/main'
      env:
        GIT_SSH_KEY: ${{ secrets.GIT_SSH_KEY }}
        GIT_NAME: ${{ secrets.GIT_NAME }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        BRANCH: gh-pages
      run: |
        mkdir -p ~/.ssh
        cat > ~/.ssh/config <<EOF
        StrictHostKeyChecking no
        LogLevel quiet
        EOF
        cat > ~/.ssh/id_rsa <<EOF
        ${GIT_SSH_KEY}
        EOF
        chmod 0600 ~/.ssh/*
        git config --global user.email "${GIT_EMAIL}"
        git config --global user.name "${GIT_NAME}"
        git clone git@github.com:making/yavi.git -b ${BRANCH}
        cd yavi
        mv .git /tmp/
        mv CNAME /tmp/
        rm -rf .
        mv /tmp/.git ./
        mv /tmp/CNAME ./
        COMMIT_MESSAGE="Update document"
        cp -r ../docs/* ./
        git diff
        git add -A
        git commit -m "${COMMIT_MESSAGE}"
        git push origin ${BRANCH}